# Generated by Django 4.0.1 on 2022-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField(max_length=10)),
                ('email_id1', models.IntegerField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField(max_length=2)),
                ('height', models.PositiveIntegerField(max_length=3)),
                ('weight', models.IntegerField()),
                ('work', models.CharField(max_length=10000)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveBigIntegerField(max_length=2)),
                ('height', models.PositiveIntegerField(max_length=3)),
                ('weight', models.PositiveBigIntegerField(max_length=3)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
