# Generated by Django 4.0.1 on 2022-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0002_alter_contractor_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='typework',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='name1',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contractor',
            name='password1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
