# Generated by Django 4.0.1 on 2022-08-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0003_typework_contractor_name1_contractor_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='email_id',
            new_name='emailid',
        ),
    ]
