# Generated by Django 4.0.1 on 2022-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0004_rename_email_id_labour_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('no_days', models.IntegerField()),
                ('no_employees_hir', models.IntegerField()),
                ('no_employees_required', models.IntegerField()),
                ('salary', models.CharField(max_length=100)),
                ('contractor', models.CharField(max_length=100)),
            ],
        ),
    ]
