# Generated by Django 4.0.1 on 2022-08-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0005_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='contractor',
            new_name='contractor_email',
        ),
    ]
