# Generated by Django 4.0.1 on 2022-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0008_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
