# Generated by Django 3.2.4 on 2022-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0009_apply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='labour',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='labour',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email_id1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labour',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labour',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
