# Generated by Django 3.2.4 on 2022-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourapi', '0010_auto_20220826_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='employ_id',
            new_name='labour_email',
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(),
        ),
    ]
